/* Pure engineering pipeline. Internal units: mm, N, N.m, rpm, W, MPa, radians. */
(function (root, factory) { var common=typeof module==='object'&&module.exports; var api=factory(common?require('../transmissions/TransmissionRegistry.js'):root.GearTransmissionRegistry); if(common)module.exports=api;else root.GearEngineering=api; })(typeof self!=='undefined'?self:this,function(Registry){
  'use strict';
  var MATERIALS={mildSteel:{name:'Acier doux',E:210000,nu:.3,density:7.85,yieldMPa:250,bendingMPa:120,contactMPa:500,friction:.06},C45:{name:'C45',E:210000,nu:.3,density:7.85,yieldMPa:430,bendingMPa:210,contactMPa:700,friction:.05},steel42CrMo4:{name:'42CrMo4',E:210000,nu:.3,density:7.85,yieldMPa:750,bendingMPa:350,contactMPa:1000,friction:.05},aluminium:{name:'Aluminium',E:70000,nu:.33,density:2.7,yieldMPa:180,bendingMPa:80,contactMPa:250,friction:.12},bronze:{name:'Bronze',E:105000,nu:.34,density:8.8,yieldMPa:220,bendingMPa:100,contactMPa:350,friction:.08},POM:{name:'POM',E:2800,nu:.35,density:1.41,yieldMPa:60,bendingMPa:35,contactMPa:70,friction:.18},PA6:{name:'PA6',E:2500,nu:.39,density:1.14,yieldMPa:55,bendingMPa:30,contactMPa:60,friction:.2},PLA:{name:'PLA imprimé',E:2500,nu:.36,density:1.24,yieldMPa:35,bendingMPa:18,contactMPa:35,friction:.2},PETG:{name:'PETG imprimé',E:2000,nu:.38,density:1.27,yieldMPa:30,bendingMPa:15,contactMPa:30,friction:.2},PEEK:{name:'PEEK',E:3700,nu:.38,density:1.3,yieldMPa:90,bendingMPa:50,contactMPa:100,friction:.16}};
  /**
   * Les SEUILS de conformité, nommés une fois.
   *
   * Ils étaient écrits en clair dans les conditions d'alerte, et récrits une
   * seconde fois dans le viewer, qui décidait donc lui-même si une mécanique
   * tient. Deux jeux de seuils finissent toujours par diverger — et le jour où
   * ils divergent, le panneau d'analyse et le dessin racontent deux mécaniques
   * différentes du même réducteur. Ils vivent ici, avec le calcul qui les
   * applique ; tout le reste les lit.
   */
  var LIMITS={bendingSafety:1.3,contactSafety:1.1,contactRatio:1.2,minTeeth:17,efficiency:.8};
  /**
   * `stageIndex` porte la PORTÉE de l'alerte : celles qui visent un étage le
   * disent, celles qui valent pour la chaîne entière le laissent nul. Sans
   * cela, le viewer ne pouvait pas savoir où poser un badge, et les recalculait
   * pour son propre compte.
   */
  function warning(level,code,message,recommendation,stageIndex){return {level:level,code:code,message:message,recommendation:recommendation,stageIndex:Number.isFinite(stageIndex)?stageIndex:null};}
  function lewisSimplified(stage,force,width,module,material,derating){var z=stage.input?stage.input.teeth:stage.sunTeeth,y=Math.max(.08,.154-.912/z);var stress=force/(width*module*y);return {method:'Simplified Lewis / Lewis simplifié',stressMPa:stress,safetyFactor:material.bendingMPa*(derating||1)/stress};}
  function hertzSimplified(stage,force,width,geometry,m1,m2,derating){var inv=(1-m1.nu*m1.nu)/m1.E+(1-m2.nu*m2.nu)/m2.E,e=1/inv,r=Math.max(1,geometry.pitchDiameterInput/2),stress=Math.sqrt(force*e/(Math.PI*width*r));return {method:'Simplified Hertz / Hertz simplifié',stressMPa:stress,safetyFactor:Math.min(m1.contactMPa,m2.contactMPa)*(derating||1)/stress};}
  /**
   * Statut d'un calcul qu'on n'a PAS fait faute de donnée. À distinguer
   * d'`unsupported`, qui dit que la famille ne sait pas le faire : « je ne sais
   * pas » et « c'est impossible » n'appellent pas la même action de la part de
   * l'utilisateur — le premier se corrige en renseignant un couple.
   */
  var NOT_EVALUATED='not-evaluated';
  var NO_FORCES={tangentialN:null,radialN:null,axialN:null};
  function analyzeStage(stage,inputTorque,options){options=options||{};var def=Registry.get(stage.type),caps=def.capabilities,g=def.calculateGeometry(stage),check=Registry.validateGeometryResult(stage,g);if(!check.valid)throw new Error('Invalid geometry: '+check.failures.join(','));
    // Sans couple d'entrée, il n'y a pas d'effort à calculer. En inventer un
    // produisait des facteurs de sécurité d'apparence sérieuse, tirés d'une
    // valeur que personne n'avait choisie.
    var known=Number.isFinite(inputTorque);
    var f=known?def.calculateForces(stage,inputTorque):NO_FORCES,m1=MATERIALS[options.inputMaterial]||MATERIALS.C45,m2=MATERIALS[options.outputMaterial]||MATERIALS.C45,width=g.width||10*(stage.parameters.module||1),module=stage.parameters.module||1,derating=options.manufacturingDerating||options.additiveDerating||1,available=known&&f&&Number.isFinite(f.tangentialN)&&f.tangentialN>0,mech={forces:f,mechanicalStatus:known?caps.forces:NOT_EVALUATED,bendingStatus:known?caps.bending:NOT_EVALUATED,contactStatus:known?caps.contact:NOT_EVALUATED,bending:null,contact:null};if(available&&caps.bending!=='unsupported')mech.bending=lewisSimplified(stage,f.tangentialN,width,module,m1,derating);if(available&&caps.contact!=='unsupported')mech.contact=hertzSimplified(stage,f.tangentialN,width,g,m1,m2,derating);return {geometry:g,mechanical:mech,efficiency:def.calculateEfficiency(stage)};}
  function dimensions(stages){var x=0,y=0,z=0,minCenter=Infinity,maxCenter=0;stages.forEach(function(s){var c=s.geometry.centerDistance||0;x+=c||s.geometry.maxDiameter||0;y=Math.max(y,s.geometry.maxDiameter||0);z=Math.max(z,s.geometry.width||0);if(c){minCenter=Math.min(minCenter,c);maxCenter=Math.max(maxCenter,c);}});return {x:x,y:y,z:z,maxDiameter:y,length:x,width:z,minCenterDistance:minCenter===Infinity?0:minCenter,maxCenterDistance:maxCenter};}
  function validateDimensions(d,c){c=c||{};var failures=[];[['maxDiameter','maxDiameter'],['length','maxLength'],['width','maxWidth'],['maxCenterDistance','maxCenterDistance']].forEach(function(k){if(c[k[1]]!=null&&d[k[0]]>c[k[1]])failures.push(k[1]);});if(c.minCenterDistance!=null&&d.minCenterDistance<c.minCenterDistance)failures.push('minCenterDistance');return {valid:!failures.length,failures:failures};}
  function score(solution,weights){weights=Object.assign({ratio:1,size:1,efficiency:1,stress:1,stages:1,noise:1,manufacturing:1,cost:1},weights||{});var evaluated=solution.mechanical.filter(function(s){return s.mechanicalStatus==='evaluated'&&s.bending;}),sf=evaluated.length?evaluated.reduce(function(v,s){return Math.min(v,s.bending.safetyFactor);},Infinity):null,unsupported=solution.mechanical.some(function(s){return s.mechanicalStatus!=='evaluated';}),values={ratio:Math.min(1,solution.errorPercent/10),size:Math.min(1,solution.dimensions.maxDiameter/500),efficiency:1-solution.efficiency,stress:sf==null?.75:Math.min(1,1/Math.max(.1,sf)+(unsupported?.15:0)),stages:solution.stages.length/8,noise:solution.stages.some(function(s){return s.type==='spur';})?.6:.25,manufacturing:solution.stages.some(function(s){return s.type==='planetary';})?.8:.3,cost:solution.stages.length/8},metrics={};Object.keys(values).forEach(function(k){var heuristic=['noise','manufacturing','cost'].indexOf(k)>=0;metrics[k]={value:values[k],confidence:heuristic?'low':'high',source:heuristic?'heuristic':'calculation'};});var sum=0,total=0;Object.keys(weights).forEach(function(k){sum+=(values[k]||0)*weights[k];total+=weights[k];});return {value:total?sum/total:0,metrics:metrics,weights:weights};}
  /**
   * Une chaîne analysée SANS conditions de service. C'était le dernier endroit
   * où le logiciel inventait en silence : 1500 rpm et 10 N·m étaient substitués
   * dès qu'ils manquaient, si bien que « étudier mon réducteur » rendait un
   * rendement, des efforts et des facteurs de sécurité tirés d'un régime que
   * personne n'avait choisi. On calcule maintenant ce qui est calculable — le
   * rapport et la géométrie ne dépendent d'aucune condition — et on laisse le
   * reste à `null`, ce qui se dit à l'écran au lieu de se deviner.
   */
  function analyzeSolution(stages,target,options){options=options||{};
    var hasSpeed=Number.isFinite(options.inputSpeedRpm),hasTorque=Number.isFinite(options.inputTorqueNm);
    var inputTorque=hasTorque?options.inputTorqueNm:null,inputSpeed=hasSpeed?options.inputSpeedRpm:null,torque=inputTorque,eff=1,analyzed=[],warnings=[];stages.forEach(function(stage,index){var a=analyzeStage(stage,torque,options);stage.geometry=a.geometry;var mechanical=Object.assign({stage:index+1,type:stage.type,ratio:Math.abs(Registry.get(stage.type).calculateRatio(stage)),signedRatio:Registry.get(stage.type).calculateRatio(stage),geometry:a.geometry,efficiency:a.efficiency},a.mechanical);analyzed.push(mechanical);eff*=a.efficiency;if(hasTorque)torque*=Math.abs(mechanical.ratio)*a.efficiency;if(a.geometry.totalContactRatio!=null&&a.geometry.totalContactRatio<LIMITS.contactRatio)warnings.push(warning('warning','LOW_CONTACT_RATIO','Rapport de conduite faible','Augmenter le nombre de dents, la largeur ou le déport.',index));if(stage.input&&stage.input.teeth<LIMITS.minTeeth+(stage.parameters.profileShiftInput||0)*-10)warnings.push(warning('warning','UNDERCUT','Sous-coupe probable','Augmenter les dents ou appliquer un déport positif.',index));if(mechanical.bending&&mechanical.bending.safetyFactor<LIMITS.bendingSafety)warnings.push(warning('danger','LOW_BENDING_SAFETY','Facteur de sécurité en flexion faible','Augmenter le module ou choisir un matériau plus résistant.',index));if(mechanical.contact&&mechanical.contact.safetyFactor<LIMITS.contactSafety)warnings.push(warning('danger','LOW_CONTACT_SAFETY','Facteur de sécurité au contact faible','Augmenter la largeur ou améliorer le matériau.',index));if(hasTorque&&Math.abs(mechanical.forces.axialN||0)>Math.abs(mechanical.forces.tangentialN||0))warnings.push(warning('warning','HIGH_AXIAL_LOAD','Effort axial élevé','Prévoir des butées et vérifier les roulements.',index));});var signedRatio=stages.reduce(function(r,s){var q=Registry.get(s.type).calculateRatio(s);return q==null?r:r*q;},1),ratio=Math.abs(signedRatio),d=dimensions(stages),solution={stages:stages,ratio:ratio,signedRatio:signedRatio,totalDirection:stages.reduce(function(d,s){var t=Registry.get(s.type);return d*(t.rotationDirection?t.rotationDirection(s):1);},1),errorPercent:Math.abs(ratio-target)/target*100,efficiency:eff,dimensions:d,inputSpeedRpm:inputSpeed,outputSpeedRpm:hasSpeed?inputSpeed/ratio:null,inputTorqueNm:inputTorque,outputTorqueNm:hasTorque?torque:null,inputPowerW:hasSpeed&&hasTorque?inputTorque*inputSpeed*2*Math.PI/60:null,mechanical:analyzed,materials:{input:options.inputMaterial||'C45',output:options.outputMaterial||'C45',additiveDerating:options.additiveDerating||1},warnings:warnings,stats:{}};// Sans puissance d'entrée, il n'y a ni pertes ni risque thermique à annoncer :
    // « faible » serait une conclusion tirée de rien.
    solution.outputPowerW=solution.inputPowerW==null?null:solution.inputPowerW*eff;solution.lossPowerW=solution.inputPowerW==null?null:solution.inputPowerW-solution.outputPowerW;solution.thermalRisk=solution.lossPowerW==null?null:solution.lossPowerW<50?'low':solution.lossPowerW<250?'medium':'high';if(solution.thermalRisk&&solution.thermalRisk!=='low')solution.warnings.push(warning('warning','THERMAL_RISK','Pertes susceptibles de provoquer un échauffement','Prévoir ventilation ou lubrification et valider thermiquement.'));if(eff<LIMITS.efficiency)solution.warnings.push(warning('warning','LOW_EFFICIENCY','Rendement global faible','Réduire les pertes ou choisir une autre architecture.'));if(hasSpeed&&options.fatigue&&options.fatigue.enabled){solution.fatigue=[];var stageRpm=inputSpeed;solution.mechanical.forEach(function(m){solution.fatigue.push(fatigue(stageRpm,options.fatigue));stageRpm/=Math.abs(m.ratio)||1;});}if(hasTorque&&options.shaft&&options.shaft.supportDistanceMm){solution.shaft=[];var stageTorque=inputTorque;solution.mechanical.forEach(function(m){solution.shaft.push(shaftEstimate(stageTorque,Math.abs(m.forces.radialN||0),options.shaft));stageTorque*=Math.abs(m.ratio)*m.efficiency;});}solution.score=score(solution,options.weights);return solution;}
  function fatigue(rpm,o){o=o||{};var hours=(o.hoursPerDay||8)*(o.daysPerYear||250)*(o.years||10),factor={constant:1,light:.8,heavy:.55,moderateShock:.4,severeShock:.25}[o.loadType||'constant'];return {cycles:rpm*60*hours,operatingHours:hours,usageFactor:factor,method:'Engineering fatigue estimate; not ISO 6336-6 compliant'};}
  function shaftEstimate(torqueNm,radialN,o){o=o||{};if(!o.supportDistanceMm)return null;var M=radialN*o.supportDistanceMm/4,T=torqueNm*1000,allow=o.allowableShearMPa||80,d=Math.cbrt(16*Math.sqrt(M*M+T*T)/(Math.PI*allow));return {bendingMomentNmm:M,torqueNmm:T,minimumDiameterMm:d,method:'Combined bending/torsion estimate'};}
  return {materials:MATERIALS,LIMITS:LIMITS,warning:warning,lewisSimplified:lewisSimplified,hertzSimplified:hertzSimplified,analyzeStage:analyzeStage,analyzeSolution:analyzeSolution,dimensions:dimensions,validateDimensions:validateDimensions,score:score,fatigue:fatigue,shaftEstimate:shaftEstimate};
});
