// Vector kinematic renderer, adapted locally from the reference project's primitive approach.
(function(GearApp){
  function KinematicLayoutEngine(){this.spacing=150;}
  KinematicLayoutEngine.prototype.layout=function(stages){return stages.map(function(s,i){return {x:90+i*150,y:105,stage:s,index:i};});};
  function KinematicRenderer(container){this.container=typeof container==='string'?document.getElementById(container):container;this.layoutEngine=new KinematicLayoutEngine();}
  KinematicRenderer.prototype.render=function(solution){var ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 '+Math.max(360,solution.length*150+100)+' 210');svg.classList.add('kinematic-svg');var nodes=this.layoutEngine.layout(solution);nodes.forEach(function(n){var type=n.stage[2]||'spur',g=document.createElementNS(ns,'g');g.setAttribute('transform','translate('+n.x+' '+n.y+')');g.setAttribute('class','kinematic-stage '+type);g.setAttribute('data-stage',n.index);var a=document.createElementNS(ns,'circle'),b=document.createElementNS(ns,'circle');a.setAttribute('r',type==='worm'?12:25);b.setAttribute('r',type==='epicyclic'?55:38);b.setAttribute('cx',type==='epicyclic'?0:55);[a,b].forEach(function(x){x.setAttribute('fill','none');x.setAttribute('stroke','currentColor');x.setAttribute('stroke-width','3');g.appendChild(x);});if(type==='helical'){var slash=document.createElementNS(ns,'path');slash.setAttribute('d','M-18 18 L18 -18 M37 28 L73 -28');slash.setAttribute('stroke','currentColor');g.appendChild(slash);}if(type==='chain'||type==='belt'){var link=document.createElementNS(ns,'path');link.setAttribute('d','M0 -25 L55 -38 M0 25 L55 38');link.setAttribute('stroke',type==='chain'?'#a66':'#777');link.setAttribute('stroke-dasharray',type==='chain'?'3 3':'');g.appendChild(link);}var text=document.createElementNS(ns,'text');text.setAttribute('y','-70');text.setAttribute('text-anchor','middle');text.textContent='Étage '+(n.index+1)+' · '+type;g.appendChild(text);svg.appendChild(g);});this.container.innerHTML='';this.container.appendChild(svg);};
  GearApp.visualization.KinematicLayoutEngine=KinematicLayoutEngine;GearApp.visualization.KinematicRenderer=KinematicRenderer;
  document.addEventListener('DOMContentLoaded',function(){var container=document.getElementById('svgContainer'),legacy=document.querySelector('.legacy-canvas-section');document.addEventListener('click',function(e){var btn=e.target.closest&&e.target.closest('.view-mode'),current=GearApp.currentSolution;if(!btn)return;document.querySelectorAll('.view-mode').forEach(function(b){b.classList.toggle('active',b===btn);});if(btn.dataset.view==='linear'){legacy.open=true;legacy.scrollIntoView({behavior:'smooth'});}else if(btn.dataset.view==='kinematic'&&current){new KinematicRenderer(container).render(current);}else if(btn.dataset.view==='geometric'&&current&&window.GearSVG){var renderer=new GearSVG('svgContainer');renderer.drawGearTrain(current,2,20);}});});
})(GearApp);
