const test=require('node:test');const assert=require('node:assert/strict');
global.GearTransmissionRegistry=require('../js/transmissions/TransmissionRegistry.js');
const R=global.GearTransmissionRegistry,E=require('../js/core/Engineering.js');
const stage=(a,b,type='spur',p={module:2,pressureAngle:20,faceWidth:20})=>R.createLegacyStage(a,b,type,p);
test('spur and compound ratios',()=>{assert.equal(R.get('spur').calculateRatio(stage(20,40)),2);assert.equal(R.get('spur').calculateRatio(stage(20,40))*R.get('spur').calculateRatio(stage(20,60)),6);});
test('worm starts are explicit and independent',()=>{let s=stage(2,60,'worm',{module:2,leadAngle:20});assert.equal(s.wormStarts,2);assert.equal(R.get('worm').calculateRatio(s),30);});
test('internal ratio and center distance',()=>{let s=stage(20,60,'internal',{module:2});assert.equal(R.get('internal').calculateRatio(s),3);assert.equal(R.get('internal').calculateGeometry(s).centerDistance,40);});
test('Willis configurations',()=>{let base={type:'planetary',sunTeeth:20,ringTeeth:60,planetTeeth:20,planetCount:4,parameters:{module:2}};assert.equal(R.get('planetary').calculateRatio({...base,inputMember:'S',outputMember:'C',fixed:'R'}),4);assert.equal(R.get('planetary').calculateRatio({...base,inputMember:'R',outputMember:'C',fixed:'S'}),4/3);assert.equal(R.get('planetary').calculateRatio({...base,inputMember:'S',outputMember:'R',fixed:'C'}),-3);assert.equal(R.get('planetary').validateConfiguration(base),true);});
test('belt length and chain even links',()=>{let b=stage(20,40,'belt',{pitch:2,centerDistance:100,beltType:'timing'}),g=R.get('belt').calculateGeometry(b);assert.ok(g.length>200);let c=stage(15,45,'chain',{pitch:12.7,centerDistance:300}),cg=R.get('chain').calculateGeometry(c);assert.equal(cg.links%2,0);assert.equal(R.get('chain').calculateRatio(c),3);});
test('rack travel',()=>{let s={type:'rack',pinionTeeth:20,parameters:{module:2,rpm:100}};assert.ok(Math.abs(R.get('rack').calculateGeometry(s).travelPerRevolution-40*Math.PI)<1e-9);});
test('geometry forces mechanics scoring and constraints',()=>{let s=stage(20,40),sol=E.analyzeSolution([s],2,{inputTorqueNm:10,inputSpeedRpm:1500,inputMaterial:'C45',outputMaterial:'C45'});assert.equal(sol.ratio,2);assert.ok(Math.abs(sol.mechanical[0].forces.tangentialN-500)<1e-9);assert.ok(sol.outputSpeedRpm===750&&sol.outputTorqueNm>19);assert.ok(sol.mechanical[0].bending.method.includes('Simplified'));assert.ok(sol.score.value>=0);assert.equal(E.validateDimensions(sol.dimensions,{maxDiameter:10}).valid,false);});
test('fatigue and shaft estimates are explicitly estimates',()=>{assert.ok(E.fatigue(1000,{}).cycles>0);assert.ok(E.shaftEstimate(10,500,{supportDistanceMm:100}).minimumDiameterMm>0);});

test('material selection changes bending and contact safety factors',()=>{const stage=R.createLegacyStage(20,60,'spur',{module:2,faceWidth:20});const steel=E.analyzeSolution([JSON.parse(JSON.stringify(stage))],3,{inputTorqueNm:20,inputMaterial:'steel42CrMo4',outputMaterial:'steel42CrMo4'});const plastic=E.analyzeSolution([JSON.parse(JSON.stringify(stage))],3,{inputTorqueNm:20,inputMaterial:'PLA',outputMaterial:'PLA'});assert.ok(steel.mechanical[0].bending.safetyFactor>plastic.mechanical[0].bending.safetyFactor);assert.ok(steel.mechanical[0].contact.safetyFactor>plastic.mechanical[0].contact.safetyFactor);});

test('solution conditionally includes per-stage fatigue and shaft estimates',()=>{const stages=[stage(20,40,'spur',{module:2}),stage(20,60,'spur',{module:2})];const solution=E.analyzeSolution(stages,6,{inputTorqueNm:10,inputSpeedRpm:1200,fatigue:{enabled:true,hoursPerDay:4,daysPerYear:200,years:5,loadType:'heavy'},shaft:{supportDistanceMm:100,allowableShearMPa:70}});assert.equal(solution.fatigue.length,2);assert.equal(solution.shaft.length,2);assert.equal(solution.fatigue[0].operatingHours,4000);assert.ok(solution.fatigue[0].cycles>solution.fatigue[1].cycles);assert.ok(solution.shaft.every(x=>x.minimumDiameterMm>0));const disabled=E.analyzeSolution([stage(20,40,'spur',{module:2})],2,{});assert.equal(disabled.fatigue,undefined);assert.equal(disabled.shaft,undefined);});
