const test=require('node:test');const assert=require('node:assert/strict');
const Search=require('../js/core/SearchEngine.js');
function params(extra={}){return Object.assign({rapportCible:3,dentMenanteMin:10,dentMenanteMax:12,dentMeneeMin:28,dentMeneeMax:36,precisionToleree:1,maxEtages:2,maxSolutions:20,maxIterations:20000,typesActifs:['spur'],typeParameters:{spur:{module:1}},allowReductionOnly:true,module:1,moduleMode:'fixed',vitesseEntree:1500,coupleEntree:2},extra);}
test('structured solution is analyzed end-to-end',()=>{const r=Search.search(params());assert.ok(r.solutions.length);const s=r.solutions[0];for(const k of ['stages','ratio','errorPercent','efficiency','dimensions','mechanical','score','warnings','inputSpeedRpm','outputSpeedRpm','inputTorqueNm','outputTorqueNm','inputPowerW','outputPowerW','lossPowerW','stats'])assert.notEqual(s[k],undefined,k);});
test('first input and last output fixed teeth are respected',()=>{const r=Search.search(params({dentMenanteFixe:11,dentMeneeFixe:33,rapportCible:3,precisionToleree:0.01}));assert.ok(r.solutions.length);for(const s of r.solutions){assert.equal(s.stages[0].input.teeth,11);assert.equal(s.stages.at(-1).output.teeth,33);}});
test('dimension rejection is counted',()=>{const r=Search.search(params({constraints:{maxDiameter:10}}));assert.equal(r.solutions.length,0);assert.ok(r.stats.rejections.dimensions>0);});
test('automatic module selects the smallest standard compatible module',()=>{const r=Search.search(params({moduleMode:'automatic',moduleMin:.8,moduleMax:2}));assert.ok(r.solutions.length);assert.equal(r.solutions[0].stats.selectedModule,.8);assert.equal(r.solutions[0].stages[0].parameters.module,.8);});
test('worm starts ignore global driving teeth range',()=>{const r=Search.search(params({rapportCible:30,dentMenanteMin:10,dentMenanteMax:10,dentMeneeMin:60,dentMeneeMax:60,typesActifs:['worm'],typeParameters:{worm:{wormStartsMin:2,wormStartsMax:2,module:1}},precisionToleree:0.01,maxEtages:1}));assert.ok(r.solutions.length);assert.equal(r.solutions[0].stages[0].wormStarts,2);});
test('invalid belt center distance never reaches results',()=>{const r=Search.search(params({typesActifs:['belt'],typeParameters:{belt:{pitch:5,centerDistance:1}},rapportCible:3}));assert.equal(r.solutions.length,0);assert.ok(r.stats.rejections.geometry>0);});
test('maxIterations counts evaluated branches',()=>{const r=Search.search(params({maxIterations:7,maxEtages:4}));assert.equal(r.stats.tested,7);});
test('search modes have distinct comparators',()=>{const a={stages:[{}],errorPercent:.2,efficiency:.8,dimensions:{x:10,y:10,z:10},mechanical:[{bending:{safetyFactor:4},contact:{safetyFactor:4}}],score:{value:.8}},b={stages:[{},{}],errorPercent:.1,efficiency:.95,dimensions:{x:20,y:20,z:20},mechanical:[{bending:{safetyFactor:2},contact:{safetyFactor:2}}],score:{value:.2}};assert.equal([a,b].sort(Search.compare('precision'))[0],b);assert.equal([a,b].sort(Search.compare('compact'))[0],a);assert.equal([a,b].sort(Search.compare('efficiency'))[0],b);assert.equal([a,b].sort(Search.compare('robust'))[0],a);assert.equal([a,b].sort(Search.compare('global'))[0],b);assert.equal([a,b].sort(Search.compare('minimumStages'))[0],a);});
test('manufacturing rules filter modules and expose applied rules',()=>{const r=Search.search(params({moduleMode:'automatic',moduleMin:.3,moduleMax:2,manufacturing:{mode:'printing3d',minimumModule:1.25,printerDiameter:500}}));assert.ok(r.solutions.length);assert.equal(r.solutions[0].stats.selectedModule,1.25);assert.equal(r.solutions[0].manufacturing.rules.mode,'printing3d');});
test('inverse constraints reject insufficient output torque and accept target 1500 to 125 rpm',()=>{const rejected=Search.search(params({rapportCible:8,dentMenanteMin:10,dentMenanteMax:10,dentMeneeMin:80,dentMeneeMax:80,precisionToleree:.01,maxEtages:1,constraints:{minimumOutputTorqueNm:1000}}));assert.equal(rejected.solutions.length,0);assert.ok(rejected.stats.rejections.mechanics>0);const accepted=Search.search(params({rapportCible:8,dentMenanteMin:10,dentMenanteMax:10,dentMeneeMin:80,dentMeneeMax:80,precisionToleree:.01,maxEtages:1,vitesseEntree:1500}));assert.equal(accepted.solutions[0].outputSpeedRpm,187.5);});
test('search pipeline carries optional fatigue and shaft estimates',()=>{const r=Search.search(params({fatigue:{enabled:true,hoursPerDay:8,daysPerYear:250,years:2,loadType:'light'},shaft:{supportDistanceMm:80,allowableShearMPa:60}}));assert.ok(r.solutions.length);assert.equal(r.solutions[0].fatigue.length,r.solutions[0].stages.length);assert.equal(r.solutions[0].shaft.length,r.solutions[0].stages.length);});
test('ratio bounds prune unreachable branches without losing compound solutions',()=>{const bounded=Search.search(params({rapportCible:9,dentMenanteMin:10,dentMenanteMax:12,dentMeneeMin:28,dentMeneeMax:36,precisionToleree:.01,maxEtages:2,searchMode:'precision',maxIterations:100000}));assert.ok(bounded.solutions.some(s=>s.stages.length===2&&Math.abs(s.ratio-9)<1e-9));const theoretical=2*Math.pow((12-10+1)*(36-28+1),2);assert.ok(bounded.stats.tested<theoretical);assert.ok(bounded.stats.rejections.ratio>0);});
test('fixed mode without a usable module reports NO_MODULES instead of failing silently',()=>{const r=Search.search(params({module:NaN}));assert.equal(r.solutions.length,0);assert.equal(r.stats.reason,'NO_MODULES');});
