const test=require('node:test');const assert=require('node:assert/strict');
const Registry=require('../js/transmissions/TransmissionRegistry.js');
const Engineering=require('../js/core/Engineering.js');
const Search=require('../js/core/SearchEngine.js');
const Manufacturing=require('../js/core/ManufacturingRules.js');
const families=['spur','helical','internal','bevel','worm','planetary','belt','chain','rack'];
function stage(type){const p={module:2,pressureAngle:20,faceWidth:20,pitch:12.7,centerDistance:200,leadAngle:20};if(type==='worm')return{type,wormStarts:2,wheelTeeth:40,parameters:p};if(type==='planetary')return{type,sunTeeth:20,planetTeeth:20,ringTeeth:60,planetCount:4,inputMember:'S',outputMember:'C',fixed:'R',parameters:p};if(type==='rack')return{type,pinionTeeth:20,parameters:{...p,rpm:100}};return{type,input:{teeth:20},output:{teeth:40},parameters:p};}
test('every V1 family declares the complete capability contract',()=>{for(const id of families){const c=Registry.get(id).capabilities;for(const key of ['ratio','geometry','forces','bending','contact','manufacturing','geometricView','kinematicView'])assert.ok(['evaluated','partial','unsupported'].includes(c[key]),`${id}.${key}`);assert.equal(typeof c.usesModule,'boolean');}});
test('evaluated mechanics are finite and unsupported results are null',()=>{for(const id of families.filter(x=>x!=='rack')){const result=Engineering.analyzeStage(stage(id),10,{}),m=result.mechanical;for(const key of ['bending','contact']){const status=m[key+'Status'],value=m[key];if(status==='evaluated'){assert.ok(Number.isFinite(value.stressMPa),id);assert.ok(Number.isFinite(value.safetyFactor),id);}if(status==='unsupported')assert.equal(value,null,id);}}});
test('unsupported safety checks reject flexible drives',()=>{for(const type of ['belt','chain']){const result=Search.search({typesActifs:[type],rapportCible:2,precisionToleree:1,maxEtages:1,maxIterations:10000,moduleMode:'automatic',dentMenanteMin:20,dentMenanteMax:20,dentMeneeMin:40,dentMeneeMax:40,typeParameters:{belt:{pitch:2,centerDistance:100},chain:{pitch:12.7,centerDistance:200}},constraints:{minimumBendingSafety:1},manufacturing:{minimumTeeth:1,minimumFaceWidth:1}});assert.equal(result.solutions.length,0,type);assert.ok(result.stats.rejections.mechanics>0,type);}});
test('belt and chain automatic searches do not iterate gear modules',()=>{for(const type of ['belt','chain']){const s=stage(type),solution={stages:[s],dimensions:{maxDiameter:100}};s.geometry=Registry.get(type).calculateGeometry(s);const report=Manufacturing.validate(solution,{minimumModule:999,minimumTeeth:1,minimumFaceWidth:1});assert.equal(report.valid,true);assert.ok(!report.appliedRules.includes('module'));}});
test('robust ranks evaluated coverage ahead of unsupported',()=>{const full={stages:[{}],errorPercent:0,mechanical:[{mechanicalStatus:'evaluated',bendingStatus:'evaluated',contactStatus:'evaluated',bending:{safetyFactor:1.1},contact:{safetyFactor:1.1}}]},unknown={stages:[{}],errorPercent:0,mechanical:[{mechanicalStatus:'unsupported',bendingStatus:'unsupported',contactStatus:'unsupported',bending:null,contact:null}]};assert.ok(Search.compare('robust')(full,unknown)<0);});
