// Read-only view of the Engineering pipeline result; no mechanical recalculation here.
(function(GearApp){
  function MechanicalPanel(id){this._container=document.getElementById(id);}
  function n(v,d){return Number.isFinite(v)?v.toFixed(d==null?2:d):'—';}
  MechanicalPanel.prototype.hide=function(){if(this._container)this._container.style.display='none';};
  MechanicalPanel.prototype.show=function(solution,unused,proMode){if(!this._container||!solution||!solution.mechanical)return null;var linear=solution.mode==='rotationTranslation',html='<h3>Analyse mécanique — Engineering estimate</h3><div class="mechanical-summary">'+
    (linear?'<div><strong>Course</strong> '+n(solution.travelPerRevolutionMm,2)+' mm/tr</div><div><strong>Vitesse linéaire</strong> '+n(solution.outputLinearSpeedMmMin,0)+' mm/min</div><div><strong>Effort sortie</strong> '+n(solution.outputForceN,1)+' N</div>':'<div><strong>Rapport</strong> '+n(solution.ratio,4)+'</div><div><strong>RPM</strong> '+n(solution.inputSpeedRpm,0)+' → '+n(solution.outputSpeedRpm,1)+'</div><div><strong>Couple</strong> '+n(solution.inputTorqueNm)+' → '+n(solution.outputTorqueNm)+' N·m</div>')+'<div><strong>Rendement</strong> '+n(solution.efficiency*100,1)+' %</div><div><strong>Puissance</strong> '+n(solution.outputPowerW,0)+' W</div><div><strong>Pertes</strong> '+n(solution.lossPowerW,0)+' W</div><div><strong>Dimensions</strong> '+n(solution.dimensions.length,0)+' × '+n(solution.dimensions.maxDiameter,0)+' × '+n(solution.dimensions.width,0)+' mm</div><div title="Coût pondéré : plus bas = mieux"><strong>Score (coût)</strong> '+n(solution.score.value,3)+'</div></div>';
    html+='<table class="stages-table"><thead><tr><th>Étage</th><th>Type</th><th>Rapport</th><th>η</th><th>Ft / Fr / Fa (N)</th><th>Lewis simplifié SF</th><th>Hertz simplifié SH</th><th>Conduite</th></tr></thead><tbody>';
    solution.mechanical.forEach(function(m,i){var f=m.forces||{},g=m.geometry||{};html+='<tr id="mechanical-stage-'+i+'"><td>'+(i+1)+'</td><td>'+m.type+'</td><td>'+n(m.ratio,3)+'</td><td>'+n(m.efficiency*100,1)+'%</td><td>'+n(f.tangentialN,0)+' / '+n(f.radialN,0)+' / '+n(f.axialN,0)+'</td><td>'+n(m.bending&&m.bending.safetyFactor,2)+'</td><td>'+n(m.contact&&m.contact.safetyFactor,2)+'</td><td>'+n(g.totalContactRatio,2)+'</td></tr>';});html+='</tbody></table>';
    if(proMode)html+='<details open><summary>Détail du score</summary><pre>'+JSON.stringify(solution.score,null,2)+'</pre></details>';
    if(proMode&&solution.fatigue)html+='<details><summary>Fatigue — Engineering estimate</summary><table class="stages-table"><thead><tr><th>Étage</th><th>Cycles</th><th>Heures</th><th>Facteur usage</th></tr></thead><tbody>'+solution.fatigue.map(function(f,i){return '<tr><td>'+(i+1)+'</td><td>'+n(f.cycles,0)+'</td><td>'+n(f.operatingHours,0)+'</td><td>'+n(f.usageFactor,2)+'</td></tr>';}).join('')+'</tbody></table><p>Estimation de fatigue, non conforme ISO 6336-6.</p></details>';
    if(proMode&&solution.shaft)html+='<details><summary>Arbres — Engineering estimate</summary><table class="stages-table"><thead><tr><th>Étage</th><th>Moment (N·mm)</th><th>Couple (N·mm)</th><th>Ø minimum (mm)</th></tr></thead><tbody>'+solution.shaft.map(function(s,i){return '<tr><td>'+(i+1)+'</td><td>'+n(s&&s.bendingMomentNmm,0)+'</td><td>'+n(s&&s.torqueNmm,0)+'</td><td>'+n(s&&s.minimumDiameterMm,2)+'</td></tr>';}).join('')+'</tbody></table><p>Estimation combinée flexion/torsion.</p></details>';
    if(solution.warnings.length)html+='<section class="warnings"><h4>Avertissements</h4>'+solution.warnings.map(function(w){return '<p class="warning"><strong>'+w.code+'</strong> — '+w.message+' <small>'+w.recommendation+'</small></p>';}).join('')+'</section>';
    this._container.innerHTML=html;
    var title=this._container.querySelector('h3'),summary=this._container.querySelector('.mechanical-summary'),stages=this._container.querySelector('.stages-table');
    var tabs=document.createElement('div');tabs.className='analysis-tabs';tabs.setAttribute('role','tablist');
    var panels=[];
    function addTab(label,node){if(!node)return;var button=document.createElement('button');button.type='button';button.textContent=label;button.setAttribute('role','tab');var panel=document.createElement('section');panel.className='analysis-panel';node.parentNode.insertBefore(panel,node);panel.appendChild(node);panels.push(panel);button.addEventListener('click',function(){Array.from(tabs.children).forEach(function(item){item.classList.toggle('active',item===button);item.setAttribute('aria-selected',String(item===button));});panels.forEach(function(item){item.hidden=item!==panel;});});tabs.appendChild(button);}
    addTab('Résumé',summary);addTab('Étages',stages);
    Array.from(this._container.querySelectorAll(':scope>details')).forEach(function(detail){addTab(detail.querySelector('summary').textContent.split('—')[0].trim(),detail);});
    addTab('Avertissements',this._container.querySelector('.warnings'));
    if(title)title.insertAdjacentElement('afterend',tabs);if(tabs.firstElementChild)tabs.firstElementChild.click();
    this._container.style.display='block';return solution;};
  GearApp.ui.MechanicalPanel=MechanicalPanel;
})(GearApp);
