(function(GearApp){'use strict';var NS='http://www.w3.org/2000/svg';
function n(tag,a,text){var e=document.createElementNS(NS,tag);Object.keys(a||{}).forEach(function(k){e.setAttribute(k,a[k]);});if(text!=null)e.textContent=text;return e;}function finite(v,d){return Number.isFinite(v)?v:d;}
function GeometryRenderer(container){this.container=typeof container==='string'?document.getElementById(container):container;this.svg=null;this.solution=null;}
GeometryRenderer.prototype.exportSVG=function(){if(!this.svg)return '';var copy=this.svg.cloneNode(true);copy.setAttribute('xmlns',NS);return new XMLSerializer().serializeToString(copy);};
GeometryRenderer.prototype.exportPNG=function(callback){if(!this.svg){callback(null);return;}var blob=new Blob([this.exportSVG()],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),image=new Image();image.onload=function(){var canvas=document.createElement('canvas');canvas.width=1200;canvas.height=600;var context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,1200,600);context.drawImage(image,0,0,1200,600);URL.revokeObjectURL(url);canvas.toBlob(callback,'image/png');};image.src=url;};
GeometryRenderer.prototype.resetView=function(){if(this.svg)this.svg.setAttribute('viewBox',this.svg.dataset.initialViewBox);};GeometryRenderer.prototype.toggleAnimation=function(){if(this.svg)this.svg.classList.toggle('is-animated');};
GeometryRenderer.prototype._circle=function(group,cx,cy,diameter,className,label){var circle=n('circle',{cx:cx,cy:cy,r:Math.max(4,diameter/2),class:className,'data-diameter-mm':diameter});circle.appendChild(n('title',{},label+' — Ø primitif '+diameter.toFixed(2)+' mm'));group.appendChild(circle);group.appendChild(n('line',{x1:cx-diameter/2,y1:cy,x2:cx+diameter/2,y2:cy,class:'pitch-diameter'}));};
GeometryRenderer.prototype._pair=function(group,stage,x,y){var g=stage.geometry;this._circle(group,x,y,g.pitchDiameterInput,'geometry-member input-member','Entrée');this._circle(group,x+g.centerDistance,y,g.pitchDiameterOutput,'geometry-member output-member','Sortie');group.dataset.centerDistanceMm=g.centerDistance;};
GeometryRenderer.prototype._internal=function(group,stage,x,y){var g=stage.geometry;this._circle(group,x,y,g.pitchDiameterOutput,'geometry-member internal-ring','Couronne');this._circle(group,x+g.centerDistance,y,g.pitchDiameterInput,'geometry-member input-member','Pignon');group.dataset.centerDistanceMm=g.centerDistance;};
GeometryRenderer.prototype._flexible=function(group,stage,x,y,chain){var g=stage.geometry,c=finite(g.correctedCenterDistance,g.centerDistance),d1=g.pitchDiameterInput,d2=g.pitchDiameterOutput,r1=d1/2,r2=d2/2,crossed=!!stage.parameters.crossed;this._circle(group,x,y,d1,'geometry-member input-member',chain?'Pignon entrée':'Poulie entrée');this._circle(group,x+c,y,d2,'geometry-member output-member',chain?'Pignon sortie':'Poulie sortie');var path=n('path',{d:crossed?'M '+x+' '+(y-r1)+' L '+(x+c)+' '+(y+r2)+' M '+x+' '+(y+r1)+' L '+(x+c)+' '+(y-r2):'M '+x+' '+(y-r1)+' L '+(x+c)+' '+(y-r2)+' M '+x+' '+(y+r1)+' L '+(x+c)+' '+(y+r2),class:chain?'chain-span':'belt-span'});group.insertBefore(path,group.firstChild);group.dataset.centerDistanceMm=c;group.dataset.crossed=String(crossed);};
GeometryRenderer.prototype._planetary=function(group,stage,x,y){var g=stage.geometry,count=stage.planetCount||3,orbit=(g.sunDiameter+g.planetDiameter)/2;this._circle(group,x,y,g.ringDiameter,'geometry-member internal-ring','R · couronne');this._circle(group,x,y,g.sunDiameter,'geometry-member input-member','S · solaire');for(var i=0;i<count;i++){var a=2*Math.PI*i/count;this._circle(group,x+Math.cos(a)*orbit,y+Math.sin(a)*orbit,g.planetDiameter,'geometry-member planet','P · satellite');}group.dataset.planetCount=count;[['ENTRÉE',stage.inputMember],['SORTIE',stage.outputMember],['FIXE',stage.fixed]].forEach(function(role,index){group.appendChild(n('text',{x:x-g.ringDiameter/2,y:y+g.ringDiameter/2+20+index*16,class:'member-role'},role[0]+' · '+role[1]));});};
GeometryRenderer.prototype._rack=function(group,stage,x,y){var g=stage.geometry,d=g.pitchDiameterInput,m=stage.parameters.module;this._circle(group,x,y-d/2,d,'geometry-member input-member','Pignon '+stage.pinionTeeth+' dents');var points=[];for(var px=x-d;px<=x+d;px+=Math.max(3,Math.PI*m/2))points.push(px+','+y,(px+Math.PI*m/4)+','+(y-7));group.appendChild(n('polyline',{points:points.join(' '),class:'rack-profile'}));group.appendChild(n('text',{x:x,y:y+28,'text-anchor':'middle',class:'geometry-dimension'},'pas '+(Math.PI*m).toFixed(2)+' mm · course '+g.travelPerRevolution.toFixed(2)+' mm/tr'));};
GeometryRenderer.prototype._bevel=function(group,stage,x,y){var g=stage.geometry,a=g.shaftAngleDeg*Math.PI/180,len=120;group.appendChild(n('line',{x1:x-150,y1:y,x2:x,y2:y,class:'shaft-axis'}));group.appendChild(n('line',{x1:x,y1:y,x2:x+Math.cos(a)*len,y2:y-Math.sin(a)*len,class:'shaft-axis'}));group.appendChild(n('text',{x:x+12,y:y-12,class:'geometry-dimension'},g.shaftAngleDeg.toFixed(1)+'°'));group.dataset.shaftAngleDeg=g.shaftAngleDeg;};
GeometryRenderer.prototype.render=function(solution){this.solution=solution;var svg=n('svg',{class:'geometry-svg',role:'img','aria-label':'Géométrie 2D calculée'}),root=n('g',{class:'geometry-viewport'}),x=120,self=this;(solution.stages||[]).forEach(function(stage,index){var group=n('g',{class:'geometry-stage '+stage.type,'data-stage':index}),g=stage.geometry||{},extent=finite(g.maxDiameter,120);if(stage.type==='internal')self._internal(group,stage,x,210);else if(stage.type==='belt'||stage.type==='chain')self._flexible(group,stage,x,210,stage.type==='chain');else if(stage.type==='planetary'||stage.type==='epicyclic')self._planetary(group,stage,x+extent/2,210);else if(stage.type==='rack')self._rack(group,stage,x+extent,260);else if(stage.type==='bevel')self._bevel(group,stage,x+120,220);else self._pair(group,stage,x,210);group.appendChild(n('text',{x:x,y:48,class:'stage-label'},'Étage '+(index+1)+' · '+stage.type));root.appendChild(group);x+=Math.max(260,extent+finite(g.centerDistance,0)+100);});var viewBox='0 0 '+Math.max(1000,x)+' 460';svg.setAttribute('viewBox',viewBox);svg.dataset.initialViewBox=viewBox;svg.appendChild(root);this.container.innerHTML='';this.container.appendChild(svg);this.svg=svg;this.container.dispatchEvent(new CustomEvent('visualization:renderer',{detail:{renderer:this}}));return this;};GearApp.visualization.GeometryRenderer=GeometryRenderer;})(GearApp);
