(function (GearApp) { 'use strict';
var NS = 'http://www.w3.org/2000/svg';
function GeometryRenderer(container) { this.container = typeof container === 'string' ? document.getElementById(container) : container; this.svg = null; this.solution = null; this.layout = null; }
GeometryRenderer.prototype.exportSVG = function () { return this.svg ? GearSvgExport.serialize(this.svg) : ''; };
GeometryRenderer.prototype.exportPNG = function (callback) { if (!this.svg) { callback(null); return; } var blob = new Blob([this.exportSVG()], { type: 'image/svg+xml' }), url = URL.createObjectURL(blob), image = new Image(); image.onload = function () { var canvas = document.createElement('canvas'); canvas.width = 1200; canvas.height = 600; var context = canvas.getContext('2d'); context.fillStyle = '#fff'; context.fillRect(0, 0, 1200, 600); context.drawImage(image, 0, 0, 1200, 600); URL.revokeObjectURL(url); canvas.toBlob(callback, 'image/png'); }; image.src = url; };
GeometryRenderer.prototype.resetView = function () { if (this.svg) this.svg.setAttribute('viewBox', this.svg.dataset.initialViewBox); };
GeometryRenderer.prototype.toggleAnimation = function () { if (this.svg) this.svg.classList.toggle('is-animated'); };
GeometryRenderer.prototype.selectStage = function (index, silent) { if (!this.svg) return; this.svg.querySelectorAll('.geometry-stage').forEach(function (group) { group.classList.toggle('selected', Number(group.dataset.stage) === index); }); if (!silent) this.container.dispatchEvent(new CustomEvent('viewer:stage-selected', { detail: { index: index } })); };
GeometryRenderer.prototype._stageGroup = function (layer, item, interactive) { var p = GearGeometryPrimitives, group = p.node('g', { class: 'geometry-stage ' + item.type, 'data-stage': item.index }); if (interactive) { var self = this; group.setAttribute('tabindex', '0'); group.setAttribute('role', 'button'); group.addEventListener('click', function () { self.selectStage(item.index); }); group.addEventListener('keydown', function (event) { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); self.selectStage(item.index); } }); } layer.appendChild(group); return group; };
GeometryRenderer.prototype._members = function (group, item) { var p = GearGeometryPrimitives, stage = item.stage, geometry = stage.geometry || {}, x = item.x, y = item.y, c = item.centerDistance;
  if (stage.type === 'planetary' || stage.type === 'epicyclic') { var count = stage.planetCount || 3, orbit = (geometry.sunDiameter + geometry.planetDiameter) / 2; p.circle(group, x, y, geometry.ringDiameter, 'geometry-member internal-ring', 'R · couronne'); p.circle(group, x, y, geometry.sunDiameter, 'geometry-member input-member', 'S · solaire'); for (var i = 0; i < count; i++) { var angle = 2 * Math.PI * i / count; p.circle(group, x + Math.cos(angle) * orbit, y + Math.sin(angle) * orbit, geometry.planetDiameter, 'geometry-member planet', 'P · satellite'); } group.dataset.planetCount = count; return; }
  if (stage.type === 'rack') { var length = Math.max(item.diameter * 2, Number(geometry.travelPerRevolution) || 0), moduleValue = Number(stage.parameters && stage.parameters.module) || 1; p.circle(group, x, y - geometry.pitchDiameterInput / 2, geometry.pitchDiameterInput, 'geometry-member input-member', 'Pignon'); p.rack(group, x, y, length, moduleValue); return; }
  if (stage.type === 'bevel') { var angleValue = geometry.shaftAngleDeg * Math.PI / 180; p.axis(group, x - 100, y, x, y); p.axis(group, x, y, x + Math.cos(angleValue) * 100, y - Math.sin(angleValue) * 100); return; }
  if (stage.type === 'internal') { p.circle(group, x, y, geometry.pitchDiameterOutput, 'geometry-member internal-ring', 'Couronne'); p.circle(group, x + c, y, geometry.pitchDiameterInput, 'geometry-member input-member', 'Pignon'); return; }
  p.circle(group, x, y, geometry.pitchDiameterInput, 'geometry-member input-member', stage.type === 'chain' ? 'Pignon entrée' : 'Entrée'); p.circle(group, x + c, y, geometry.pitchDiameterOutput, 'geometry-member output-member', stage.type === 'chain' ? 'Pignon sortie' : 'Sortie');
};
GeometryRenderer.prototype._flexible = function (group, item) { var p = GearGeometryPrimitives, stage = item.stage, geometry = stage.geometry, exact = GearGeometryUtils.flexiblePath({ x: item.x, y: item.y }, { x: item.x + item.centerDistance, y: item.y }, geometry.pitchDiameterInput / 2, geometry.pitchDiameterOutput / 2, !!(stage.parameters && stage.parameters.crossed)); var pathData = exact.tangents.map(function (tangent) { return 'M ' + tangent.from.x.toFixed(3) + ' ' + tangent.from.y.toFixed(3) + ' L ' + tangent.to.x.toFixed(3) + ' ' + tangent.to.y.toFixed(3); }).join(' '); group.appendChild(p.node('path', { d: pathData, class: stage.type === 'chain' ? 'chain-span' : 'belt-span' })); group.dataset.centerDistanceMm = exact.distance; group.dataset.wrapAngleDeg = (exact.wrapAngle1 * 180 / Math.PI).toFixed(2); group.dataset.crossed = String(exact.crossed); };
GeometryRenderer.prototype.render = function (solution) { this.solution = solution; this.layout = GearGeometryLayout.build(solution); var p = GearGeometryPrimitives, svg = p.node('svg', { class: 'geometry-svg', role: 'img', 'aria-label': 'Géométrie 2D calculée' }), viewport = p.node('g', { class: 'geometry-viewport' }), names = ['envelope', 'shaft', 'geometry', 'pitch', 'dimension', 'force', 'label'], layers = {}; names.forEach(function (name) { layers[name] = p.node('g', { class: name + '-layer' }); viewport.appendChild(layers[name]); }); var self = this;
  GearDimensionRenderer.envelope(layers.envelope, this.layout, p); this.layout.stages.forEach(function (item) { var members = self._stageGroup(layers.geometry, item, true), dimensions = self._stageGroup(layers.dimension, item, false), axes = self._stageGroup(layers.shaft, item, false), labels = self._stageGroup(layers.label, item, false); p.axis(axes, item.x - item.diameter / 2 - 20, item.y, item.x + item.width + 20, item.y); if (item.type === 'belt' || item.type === 'chain') self._flexible(members, item); self._members(members, item); GearDimensionRenderer.stage(dimensions, item, p); labels.appendChild(p.node('text', { x: item.x - item.diameter / 2, y: 35, class: 'stage-label' }, 'Étage ' + (item.index + 1) + ' · ' + item.type)); });
  var box = '0 0 ' + this.layout.bounds.width + ' ' + this.layout.bounds.height; svg.setAttribute('viewBox', box); svg.dataset.initialViewBox = box; svg.appendChild(viewport); this.container.innerHTML = ''; this.container.appendChild(svg); this.svg = svg; this.container.dispatchEvent(new CustomEvent('visualization:renderer', { detail: { renderer: this } })); return this; };
GearApp.visualization.GeometryRenderer = GeometryRenderer;
})(GearApp);
