// Compatibility adapter. All equations and constraints live in transmissions/TransmissionRegistry.js.
(function(GearApp){
  'use strict';
  var labels={spur:['Engrenage droit','Droit'],helical:['Engrenage hélicoïdal','Hélicoïdal'],internal:['Engrenage intérieur','Intérieur'],bevel:['Engrenage conique','Conique'],belt:['Courroie','Courroie'],planetary:['Train épicycloïdal','Épicycloïdal'],worm:['Vis sans fin','Vis sans fin'],chain:['Chaîne','Chaîne'],rack:['Crémaillère','Crémaillère']};
  function adapt(id){var canonical=id==='epicyclic'?'planetary':id,def=GearTransmissionRegistry.get(canonical)||GearTransmissionRegistry.get('spur'),names=labels[canonical]||[def.name,def.name];return {id:id,nom:names[0],nomCourt:names[1],description:def.name,icone:'⚙',couleur:'#d4e6f1',uniteA:canonical==='worm'?'filets':'dents',uniteB:'dents',axesRelation:canonical==='planetary'?'coaxial':(canonical==='worm'||canonical==='bevel'?'perpendicular':'parallel'),contraintes:{minA:def.constraints.minInput,maxA:def.constraints.maxInput,minB:def.constraints.minOutput,maxB:def.constraints.maxOutput,minRapportEtage:0,maxRapportEtage:def.constraints.maxRatio},paramsSupplementaires:[],calculerRapport:function(A,B,params){return def.calculateRatio(GearTransmissionRegistry.createLegacyStage(A,B,canonical,normalize(params)));},calculerRendement:function(A,B,params){return def.calculateEfficiency(GearTransmissionRegistry.createLegacyStage(A,B,canonical,normalize(params)));},calculerGeometrie:function(A,B,m,params){var g=def.calculateGeometry(GearTransmissionRegistry.createLegacyStage(A,B,canonical,Object.assign(normalize(params),{module:m})));return Object.assign({type:id,entraxe:g.centerDistance,diamPrimitiveA:g.pitchDiameterInput||g.sunDiameter,diamPrimitiveB:g.pitchDiameterOutput||g.ringDiameter,diamTeteA:g.outsideDiameterInput||g.pitchDiameterInput,diamTeteB:g.outsideDiameterOutput||g.pitchDiameterOutput,pas:g.circularPitch},g);},sensRotation:function(A,B,params){return def.rotationDirection(GearTransmissionRegistry.createLegacyStage(A,B,canonical,normalize(params)));}};}
  function normalize(p){p=p||{};return {module:p.module||1,pressureAngle:p.angleContact||p.pressureAngle||20,helixAngle:p.angleHelice||p.helixAngle||20,leadAngle:p.angleAvance||p.leadAngle||20,frictionCoefficient:p.coeffFrottement||.06,centerDistance:p.entraxeCourroie||p.centerDistance||100,pitch:p.pitch||2,beltType:p.typeCourroie||p.beltType||'timing',crossed:p.courroieCroisee||p.crossed,planetCount:p.nbSatellites||p.planetCount||3,inputMember:p.inputMember||'S',outputMember:p.outputMember||'C',fixed:p.fixed||'R'};}
  function TransmissionTypeRegistry(){this._cache={};}
  TransmissionTypeRegistry.prototype.get=function(id){id=id||'spur';return this._cache[id]||(this._cache[id]=adapt(id));};
  TransmissionTypeRegistry.prototype.list=function(){var self=this;return GearTransmissionRegistry.list().map(function(d){return self.get(d.id);});};
  TransmissionTypeRegistry.prototype.calculerRapportEtage=function(id,A,B){return this.get(id).calculerRapport(A,B);};
  TransmissionTypeRegistry.prototype.validerCombinaison=function(id,A,B){var t=this.get(id),c=t.contraintes;return A>=c.minA&&A<=c.maxA&&B>=c.minB&&B<=c.maxB&&isFinite(t.calculerRapport(A,B));};
  var registry=new TransmissionTypeRegistry();GearApp.models.typeRegistry=registry;GearApp.models.TransmissionTypeRegistry=TransmissionTypeRegistry;
  window.getTransmissionTypesList=function(){return registry.list();};window.getTransmissionType=function(id){return registry.get(id);};window.calculerRapportEtage=function(id,A,B){return registry.calculerRapportEtage(id,A,B);};window.validerCombinaison=function(id,A,B){return registry.validerCombinaison(id,A,B);};
})(GearApp);
